FROM ubuntu:20.04

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/

RUN apt-get update -y \
    && apt-get install -y software-properties-common \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt-get install openjdk-8-jdk -y \
    && apt-get install python3-pip -y \
    && export JAVA_HOME \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

#ENV PYSPARK_PYTHON=/usr/bin/python3

ENV PYSPARK_PYTHON python3

WORKDIR /home/user/pjt_final/happy-or-sad-tweet/
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
COPY streamlit/app.py streamlit/app.py
COPY .env .
CMD [ "streamlit","run","streamlit/app.py"]