FROM python:3.9

WORKDIR /home/user/pjt_final/happy-or-sad-tweet/

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY streamlit/app.py streamlit/app.py

CMD [ "python3","streamlit/app.py"]